// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZgGYb12k4LVf7f9bi05XRisi78P2UP3k',
    appId: '1:849229927171:web:10c0621e8331af692b0f36',
    messagingSenderId: '849229927171',
    projectId: 'echo-app-4163f',
    authDomain: 'echo-app-4163f.firebaseapp.com',
    storageBucket: 'echo-app-4163f.firebasestorage.app',
    measurementId: 'G-FXH3E1EFVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcFmyrL7DOYtv818WmZqZCW4_uj_fGa0',
    appId: '1:849229927171:android:b54e04670448b0382b0f36',
    messagingSenderId: '849229927171',
    projectId: 'echo-app-4163f',
    storageBucket: 'echo-app-4163f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qYiQGnokzwjYKO5q_7ymgiftqDSVCP4',
    appId: '1:849229927171:ios:c8c1a86f5ee3c7692b0f36',
    messagingSenderId: '849229927171',
    projectId: 'echo-app-4163f',
    storageBucket: 'echo-app-4163f.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qYiQGnokzwjYKO5q_7ymgiftqDSVCP4',
    appId: '1:849229927171:ios:c8c1a86f5ee3c7692b0f36',
    messagingSenderId: '849229927171',
    projectId: 'echo-app-4163f',
    storageBucket: 'echo-app-4163f.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZgGYb12k4LVf7f9bi05XRisi78P2UP3k',
    appId: '1:849229927171:web:e2e7da2df17592ad2b0f36',
    messagingSenderId: '849229927171',
    projectId: 'echo-app-4163f',
    authDomain: 'echo-app-4163f.firebaseapp.com',
    storageBucket: 'echo-app-4163f.firebasestorage.app',
    measurementId: 'G-428H5RL8XT',
  );
}
